version: 2

updates:
    - package-ecosystem: github-actions

      directory: "/"

      schedule:
          interval: daily

      target-branch: main

    - directory: "/"

      package-ecosystem: mix

      schedule:
          interval: daily

      target-branch: main
